[package]
name = "voxel-maths"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.23.0", features = ["must_cast_extra", "min_const_generics", "derive"] }
glam = "0.30.3"
cfg-if = "1.0.0"
likely_stable = "0.1.3"


[dev-dependencies]
proptest = "1.6.0"